/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelsView;

import Handler.AdminHandler;
import Handler.Language;
import Handler.SystemHandler;
import UtilityStuff.Listeners;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author markh
 */
public class CardLayoutView extends javax.swing.JPanel {

    private CardLayout cardLayout;
    private PlanView planViewPanel;
    private Language language;
    private Listeners listeners;
    private SystemHandler systemHandler;
    private AdminHandler adminHandler;
    private AdminView adminView;
    private MealsPlanView mealsPlanView;
    private IngredientsView ingredientsView;

    /**
     * Creates new form PlanView
     */
    public CardLayoutView() {
        planViewPanel = new PlanView();
        adminView = new AdminView();
        mealsPlanView = new MealsPlanView();
        ingredientsView = new IngredientsView();
        listeners = Listeners.getList();
        language = Language.getInstance();
        try {
            systemHandler = SystemHandler.getInstance();
            adminHandler = AdminHandler.getInstance();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CardLayoutView.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setSize(new Dimension(1385, 760));
        cardLayout = (CardLayout) jP_card.getLayout();
        cardLayout.addLayoutComponent(jP_admin, "Admin");
        cardLayout.addLayoutComponent(jP_Meals, "Meals");
        cardLayout.addLayoutComponent(jP_ingre, "Ingredients");
        jP_admin.add(adminView);
        jP_Meals.add(mealsPlanView);
        jP_ingre.add(ingredientsView);
        cardLayout.show(jP_card, "Meals");
        jT_dishes.setSelected(true);
        buttomLanguage();
        jT_admin.setEnabled(adminHandler.isAdminLogon());
    }
    
    private void chancePage(String page){
        cardLayout.show(jP_card, page);
    }

    private void buttomLanguage() {
        if (language.getLanguage()) {
            jT_dishes.setText("Meals");
            jT_favorite.setText("Favorite Meals");
            jT_dislike.setText("Dislike Meals");
            jT_Ingredients.setText("Ingredients");
            jT_information.setText("Alter Infomation");
            jT_admin.setText("User Infomation");
            jB_logout.setText("Logout");
        } else {
            jT_dishes.setText("Retter");
            jT_favorite.setText("Favorit Retter");
            jT_dislike.setText("Dårlige Retter");
            jT_Ingredients.setText("Vare");
            jT_information.setText("Ændre Info");
            jT_admin.setText("Bruger Info");
            jB_logout.setText("Log Ud");
        }
    }

    private void selectToogleButtom(String pushedButtom) {
        jT_Ingredients.setSelected(false);
        jT_admin.setSelected(false);
        jT_dishes.setSelected(false);
        jT_dislike.setSelected(false);
        jT_favorite.setSelected(false);
        jT_information.setSelected(false);

        switch (pushedButtom) {
            case "ingredients":
                jT_Ingredients.setSelected(true);
                break;
            case "admin":
                jT_admin.setSelected(true);
                chancePage("Admin");
                break;
            case "dishes":
                jT_dishes.setSelected(true);
                break;
            case "dislike":
                jT_dislike.setSelected(true);
                break;
            case "favorite":
                jT_favorite.setSelected(true);
                break;
            case "information":
                jT_information.setSelected(true);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_card = new javax.swing.JPanel();
        jP_admin = new javax.swing.JPanel();
        jP_Meals = new javax.swing.JPanel();
        jP_ingre = new javax.swing.JPanel();
        jT_dishes = new javax.swing.JToggleButton();
        jT_Ingredients = new javax.swing.JToggleButton();
        jT_information = new javax.swing.JToggleButton();
        jT_admin = new javax.swing.JToggleButton();
        jB_logout = new javax.swing.JButton();
        jT_favorite = new javax.swing.JToggleButton();
        jT_dislike = new javax.swing.JToggleButton();

        jP_card.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jP_adminLayout = new javax.swing.GroupLayout(jP_admin);
        jP_admin.setLayout(jP_adminLayout);
        jP_adminLayout.setHorizontalGroup(
            jP_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        jP_adminLayout.setVerticalGroup(
            jP_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jP_card.add(jP_admin, "card2");

        javax.swing.GroupLayout jP_MealsLayout = new javax.swing.GroupLayout(jP_Meals);
        jP_Meals.setLayout(jP_MealsLayout);
        jP_MealsLayout.setHorizontalGroup(
            jP_MealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        jP_MealsLayout.setVerticalGroup(
            jP_MealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jP_card.add(jP_Meals, "card3");

        javax.swing.GroupLayout jP_ingreLayout = new javax.swing.GroupLayout(jP_ingre);
        jP_ingre.setLayout(jP_ingreLayout);
        jP_ingreLayout.setHorizontalGroup(
            jP_ingreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        jP_ingreLayout.setVerticalGroup(
            jP_ingreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jP_card.add(jP_ingre, "card4");

        jT_dishes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_dishes.setText("jToggleButton1");
        jT_dishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_dishesActionPerformed(evt);
            }
        });

        jT_Ingredients.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_Ingredients.setText("jToggleButton2");
        jT_Ingredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_IngredientsActionPerformed(evt);
            }
        });

        jT_information.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_information.setText("jToggleButton3");
        jT_information.setEnabled(false);
        jT_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_informationActionPerformed(evt);
            }
        });

        jT_admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_admin.setText("jToggleButton4");
        jT_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_adminActionPerformed(evt);
            }
        });

        jB_logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_logout.setText("jButton1");
        jB_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logoutActionPerformed(evt);
            }
        });

        jT_favorite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_favorite.setText("jToggleButton1");
        jT_favorite.setEnabled(false);
        jT_favorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_favoriteActionPerformed(evt);
            }
        });

        jT_dislike.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_dislike.setText("jToggleButton1");
        jT_dislike.setEnabled(false);
        jT_dislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_dislikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jT_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jT_dishes, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jT_Ingredients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jT_favorite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jT_dislike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jP_card, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_card, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jT_dishes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_favorite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_dislike, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_Ingredients, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_information, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logoutActionPerformed
        listeners.notifyListeners("Logout");
    }//GEN-LAST:event_jB_logoutActionPerformed

    private void jT_dishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_dishesActionPerformed
        selectToogleButtom("dishes");
        chancePage("Meals");
        
    }//GEN-LAST:event_jT_dishesActionPerformed

    private void jT_favoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_favoriteActionPerformed
        selectToogleButtom("favorite");
    }//GEN-LAST:event_jT_favoriteActionPerformed

    private void jT_dislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_dislikeActionPerformed
        selectToogleButtom("dislike");
    }//GEN-LAST:event_jT_dislikeActionPerformed

    private void jT_IngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_IngredientsActionPerformed
        selectToogleButtom("ingredients");
        chancePage("Ingredients");
    }//GEN-LAST:event_jT_IngredientsActionPerformed

    private void jT_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_informationActionPerformed
        selectToogleButtom("information");
    }//GEN-LAST:event_jT_informationActionPerformed

    private void jT_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_adminActionPerformed
        selectToogleButtom("admin");
        chancePage("Admin");
    }//GEN-LAST:event_jT_adminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_logout;
    private javax.swing.JPanel jP_Meals;
    private javax.swing.JPanel jP_admin;
    private javax.swing.JPanel jP_card;
    private javax.swing.JPanel jP_ingre;
    private javax.swing.JToggleButton jT_Ingredients;
    private javax.swing.JToggleButton jT_admin;
    private javax.swing.JToggleButton jT_dishes;
    private javax.swing.JToggleButton jT_dislike;
    private javax.swing.JToggleButton jT_favorite;
    private javax.swing.JToggleButton jT_information;
    // End of variables declaration//GEN-END:variables
}
