/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelsView;

import Handler.SystemHandler;
import UtilityStuff.Listeners;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author markh
 */
public class LogonView extends javax.swing.JPanel {

    private SystemHandler systemHandler;
    private Listeners listeners;

    /**
     * Creates new form LogonView
     */
    public LogonView() {
        listeners = Listeners.getList();

        this.setSize(250, 300);
        initComponents();
        try {
            systemHandler = SystemHandler.getInstance();
        } catch (ClassNotFoundException | SQLException ex) {
            jL_Welcome.setText("Problem Whit DB Connection");
            System.out.println(ex.getLocalizedMessage());
        }
    }

    public void Logon() {
        boolean logon = systemHandler.logon(jT_Username.getText(), Integer.parseInt(jT_Password.getText()));

        if (logon) {
            listeners.notifyListeners("Logon succseed");
        } else {
            jL_Welcome.setForeground(Color.red);
            jL_Welcome.setText("Incorrect information");
        }
    }
    
    private void createUser(){
        listeners.notifyListeners("Create new user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Welcome = new javax.swing.JLabel();
        jT_Username = new javax.swing.JTextField();
        jT_Password = new javax.swing.JTextField();
        jB_Logon = new javax.swing.JButton();
        jB_NewUser = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Logon", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jL_Welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Welcome.setText("Welcome. Please logon");

        jT_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_Username.setText("english");
        jT_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_UsernameActionPerformed(evt);
            }
        });
        jT_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_UsernameFocusLost(evt);
            }
        });

        jT_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jT_Password.setText("1111");
        jT_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_PasswordFocusLost(evt);
            }
        });

        jB_Logon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Logon.setText("Logon");
        jB_Logon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LogonActionPerformed(evt);
            }
        });

        jB_NewUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_NewUser.setText("New User");
        jB_NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_NewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jT_Username)
                    .addComponent(jT_Password)
                    .addComponent(jB_Logon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_NewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jT_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Logon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_NewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_UsernameFocusGained
        if (jT_Username.getText().equals("Username")) {
            jT_Username.setText("");
        }
    }//GEN-LAST:event_jT_UsernameFocusGained

    private void jT_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_UsernameFocusLost
        if (jT_Username.getText().equals("")) {
            jT_Username.setText("Username");
        }
    }//GEN-LAST:event_jT_UsernameFocusLost

    private void jT_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_PasswordFocusGained
        if (jT_Password.getText().equals("Password")) {
            jT_Password.setText("");
        }
    }//GEN-LAST:event_jT_PasswordFocusGained

    private void jT_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_PasswordFocusLost
        if (jT_Password.getText().equals("")) {
            jT_Password.setText("Password");
        }
    }//GEN-LAST:event_jT_PasswordFocusLost

    private void jB_LogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LogonActionPerformed
        Logon();
    }//GEN-LAST:event_jB_LogonActionPerformed

    private void jB_NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_NewUserActionPerformed
        createUser();
    }//GEN-LAST:event_jB_NewUserActionPerformed

    private void jT_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_UsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Logon;
    private javax.swing.JButton jB_NewUser;
    private javax.swing.JLabel jL_Welcome;
    private javax.swing.JTextField jT_Password;
    private javax.swing.JTextField jT_Username;
    // End of variables declaration//GEN-END:variables
}
